name: Flutter Version Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Get Version from PR branch
      id: get-pr-version
      run: |
        PR_VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //')
        echo "PR_VERSION=$PR_VERSION" >> $GITHUB_ENV
        echo "The new version is ${{ env.PR_VERSION }}"

    - uses: actions/checkout@v4
      with:
        ref: main

    - name: Get Version from Main branch
      id: get-main-version
      run: |
        MAIN_VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //')
        echo "MAIN_VERSION=$MAIN_VERSION" >> $GITHUB_ENV
        echo "The version in main is ${{ env.MAIN_VERSION }}"

    - name: Compare Versions
      run: |
        PR_VERSION_NUMBER=$(echo ${PR_VERSION#*+} | cut -d '.' -f 1)
        MAIN_VERSION_NUMBER=$(echo ${MAIN_VERSION#*+} | cut -d '.' -f 1)

        if [[ -z "$PR_VERSION_NUMBER" ]]; then
          PR_VERSION_NUMBER=0
        fi

        if [[ -z "$MAIN_VERSION_NUMBER" ]]; then
          MAIN_VERSION_NUMBER=0
        fi

        if [[ "$PR_VERSION_NUMBER" -le "$MAIN_VERSION_NUMBER" ]]; then
          echo "Fail - Build number $PR_VERSION_NUMBER must be larger than $MAIN_VERSION_NUMBER."
          exit 1
        fi
        echo "Pass - Build number $PR_VERSION_NUMBER is larger than $MAIN_VERSION_NUMBER."